### ISSUE TITLE
[FEATURE] Support for rate limit for specific path 

### ISSUE THREAD

**Issue by rs324** [zufardhiyaulhaq/istio-ratelimit-operator#16]
**Is your feature request related to a problem? Please describe.**
We need to provide ratelimit by path or method (put for example) on the application and not for the entire application.

**Describe the solution you'd like**
my config should look like the following example:

```
config.yaml: |
    domain: http-bin-server-ratelimit-config
    descriptors:
    - key: path
      value: /ip
      rate_limit:
        unit: hour
        requests_per_unit: 1
```

Thank you
